Kyonggi-Univ-Diet-Information/BE

build.gradle, src/main/java/com/kyonggi/diet/member/MemberController.java, src/main/java/com/kyonggi/diet/member/MemberDTO.java, src/main/java/com/kyonggi/diet/member/MemberEntity.java, src/main/java/com/kyonggi/diet/member/MemberRepository.java, src/main/java/com/kyonggi/diet/member/io/MemberRequest.java, src/main/java/com/kyonggi/diet/member/io/MemberResponse.java, src/main/java/com/kyonggi/diet/member/service/MemberService.java, src/main/java/com/kyonggi/diet/member/service/impl/MemberServiceImpl.java
#6 
- spring security와 validation 사용을 위한 dependencies 추가
- member request에 validation 추가
- member 회원가입을 위한 서비스와 컨트롤러 로직 추가 (테스트 완료)
-member entity에 기존 Long id 이외에 UUID를 사용하는 String member_id가 추가되었습니다
=> [FEAT] create register logic

build.gradle, src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java, src/main/java/com/kyonggi/diet/swagger/SwaggerConfig.java
#27 
- swagger 기본 설정 적용
- auth 토큰 적용 시 authorize 잠금 해제 (활성화)
추가 설정 필요 시 추후 적용
=> Feat: create swagger

.gitignore, Dockerfile, Jenkinsfile
#23 
- application.yaml 파일 .gitignore에 추가
- jenkins pipeline 생성
- java app build하는 docker 생성
머지 후 작동 테스트 필요
- Jenkins에 환경변수 설정 후 테스트
- aws ecr 및 ecs 배포 확인
- docker file 에서도 수행하는 빌드 필요 없으면 삭제
=> [FEAT] create pipeline

Jenkinsfile
=> [FIX] add quote

Jenkinsfile, src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java
HTTPS 통신으로 변경한 뒤 젠킨스 to 깃허브 접근 에러 발생
젠킨스가 깃허브 토큰 사용하도록 변경
=> [FEAT] add github credential for https

Jenkinsfile
여전히 jenkins to github 접근 에러 발생
인증을 위해 깃허브 플러그인 사용
=> [FIX] use github plugin

Jenkinsfile
=> [FIX] rollback code

.gitignore, build.gradle, src/main/java/com/kyonggi/diet/aws/CSVServices.java, src/main/java/com/kyonggi/diet/aws/S3Config.java, src/main/java/com/kyonggi/diet/aws/S3FileRequest.java, src/main/java/com/kyonggi/diet/dietFile/CSVController.java, src/main/resources/application.yml, src/main/resources/local.env
csv읽는 방식 변경
로컬 내 파일 읽는 것 -> s3 파일 읽기 로 변경
테스트를 위해 이전 로컬 방식을 남겨뒀습니다
=> feat:change-csv-reader

Jenkinsfile
Jenkins 파이프라인에서 환경변수에 접근하지 못하는 문제 발생
Jenkins 파이프라인에서 환경변수 사용 가능하도록 추가
=> [FEAT] Jenkins 파이프라인 환경변수 추가

Jenkinsfile, src/main/java/com/kyonggi/diet/auth/KakaoAuthController.java, src/main/java/com/kyonggi/diet/auth/config/CorsConfig.java, src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java, src/main/resources/application.yml, src/main/resources/data.sql
#25
CSV read test 결과 S3 Bucket 을 못 찾는 에러 발생
Jenkins 정상화 및 Kakao login setup을 진행했습니다.
=> [FEAT] CSV read test and kakao-login setup

src/main/java/com/kyonggi/diet/controllerDocs/DietContentControllerDocs.java, src/main/java/com/kyonggi/diet/dietContent/DietContentController.java
dietContent 컨틀롤러 내 키 값 추가
최상단이 요일로 묶음 -> result 키값으로 묶음
=> [FEAT] make one more key

src/main/java/com/kyonggi/diet/auth/HealthController.java, src/main/java/com/kyonggi/diet/auth/KakaoAuthService.java, src/main/java/com/kyonggi/diet/auth/config/CorsConfig.java, src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java, src/main/java/com/kyonggi/diet/member/MemberEntity.java, src/main/resources/application.yml
변경된 도메인에 따른 추가 CORS 셋팅
- CORS configuration
- add log to kakao-service
로그는 개발 단계에서만 사용
=> [FEAT] 카카오 로그인 CORS

src/main/java/com/kyonggi/diet/review/favoriteReview/controller/FavoriteDietFoodReviewController.java, src/main/java/com/kyonggi/diet/review/favoriteReview/controller/FavoriteRestaurantReviewController.java, src/main/java/com/kyonggi/diet/review/favoriteReview/domain/FavoriteDietFoodReview.java, src/main/java/com/kyonggi/diet/review/favoriteReview/domain/FavoriteRestaurantReview.java, src/main/java/com/kyonggi/diet/review/favoriteReview/repository/FavoriteDietFoodReviewRepository.java, src/main/java/com/kyonggi/diet/review/favoriteReview/repository/FavoriteRestaurantReviewRepository.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/FavoriteDietFoodReviewService.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/FavoriteRestaurantReviewService.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/impl/FavoriteDietFoodReviewServiceImpl.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/impl/FavoriteRestaurantReviewServiceImpl.java
관심 리뷰를 취소하는 메서드 구현
- 관심 리뷰 취소 가능하게 추가
- 관심 리뷰를 여러 사람이 생성하면 중복 에러가 뜨는 오류 수정 (도메인 내 OneToOne을 ManyToOne으로 수정)
- 리뷰 좋아요 생성 시 null값에 대한 예외 처리
=> [Feat] 리뷰 좋아요 취소 기능 추가

src/main/java/com/kyonggi/diet/auth/KakaoAuthService.java, src/main/java/com/kyonggi/diet/member/service/CustomMembersDetailService.java
카카오 회원가입을 진행한 유저 데이터로 JWT token을 발급하는 경우 에러 발생
- 서비스 계층에서 유저 정보를 가져올 때 비밀번호를 가져오지 않도록 합니다.
=> [FIX] 카카오 로그인 + 스프링 시큐리티 이슈 해결

src/main/java/com/kyonggi/diet/controllerDocs/DietFoodReviewControllerDocs.java, src/main/java/com/kyonggi/diet/review/controller/DietFoodReviewController.java, src/main/java/com/kyonggi/diet/review/repository/DietFoodReviewRepository.java, src/main/java/com/kyonggi/diet/review/service/DietFoodReviewService.java, src/main/java/com/kyonggi/diet/review/service/Impl/DietFoodReviewServiceImpl.java
음식 아이디로 리뷰 리스트 구하기
특정 음식 아이디를 통해 요청을 하면 해당 음식의 리뷰 리스트를 반환 받는 로직 구현
=> feat: add dietFood List service

src/main/java/com/kyonggi/diet/controllerDocs/DietFoodReviewControllerDocs.java, src/main/java/com/kyonggi/diet/review/DTO/ReviewDTO.java, src/main/java/com/kyonggi/diet/review/controller/DietFoodReviewController.java, src/main/java/com/kyonggi/diet/review/repository/DietFoodReviewRepository.java, src/main/java/com/kyonggi/diet/review/repository/RestaurantReviewRepository.java, src/main/java/com/kyonggi/diet/review/service/DietFoodReviewService.java, src/main/java/com/kyonggi/diet/review/service/Impl/DietFoodReviewServiceImpl.java
음식 리뷰에 대한 평점을 구한다
각 음식 리뷰에 대해서 리뷰 평점을 구하는 로직 구현
리뷰 DTO에 id값 추가하여 다른 메서드 이용시(수정, 삭제 등) 사용 가능하도록 하였습니다. 
식당 리뷰 평점의 경우 아직 기숙사 식당만 유지되기에 아직 적용하지 않았습니다
=> feat: get rating average for dietFoodReviw

src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java
=> feat:add cors

src/main/java/com/kyonggi/diet/controllerDocs/DietFoodReviewControllerDocs.java, src/main/java/com/kyonggi/diet/review/controller/DietFoodReviewController.java, src/main/java/com/kyonggi/diet/review/service/Impl/DietFoodReviewServiceImpl.java
음식 리뷰 컨트롤러 내 반환형 변경
음식 리뷰 컨트롤러 내에 있는 메서드의 반환형을 DTO에서 ResponseEntity로 변경함으로써 401에러 나오는 문제 해결
빠른 작업을 위해 음식 리뷰에 우선적으로 적용했고, 식당 리뷰도 작업하겠습니다
=> fix: fix return type in diet food review controller to prevent 401 error

src/main/java/com/kyonggi/diet/review/DTO/ReviewDTO.java, src/main/java/com/kyonggi/diet/review/service/Impl/DietFoodReviewServiceImpl.java
리뷰 dto 내에 생성 일자, 수정 일자 추가
리뷰 dto 내에 생성 일자 및 수정 일자 (String 자료형) 으로 추가
=> refactor: add createdAt, updatedAt (String) to ReviewDTO

src/main/java/com/kyonggi/diet/dietFile/CSVService.java, src/main/java/com/kyonggi/diet/review/controller/DietFoodReviewController.java
리뷰 오류로 인한 로그 추가
리뷰 오류로 인한 로그 추가
=> feat: add review log

src/main/java/com/kyonggi/diet/controllerDocs/FavoriteDietFoodReviewControllerDocs.java, src/main/java/com/kyonggi/diet/review/favoriteReview/controller/FavoriteDietFoodReviewController.java, src/main/java/com/kyonggi/diet/review/favoriteReview/repository/FavoriteDietFoodReviewRepository.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/FavoriteDietFoodReviewService.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/impl/FavoriteDietFoodReviewServiceImpl.java
음식 리뷰 좋아요 관련 서비스 및 컨트롤러 예외 처리
음식 리뷰 좋아요 관련 서비스 및 컨트롤러 예외 처리 강화
=> refactor: add exception for favorite diet food review

src/main/java/com/kyonggi/diet/review/favoriteReview/controller/FavoriteDietFoodReviewController.java
메서드가 post로 되어있었던 것 get으로 변경 
메서드가 post로 되어있었던 것 get으로 변경
=> fix: fix post to get

src/main/java/com/kyonggi/diet/review/favoriteReview/controller/FavoriteDietFoodReviewController.java
=> fix: add little spell

src/main/java/com/kyonggi/diet/review/favoriteReview/DTO/FavoriteDietFoodReviewDTO.java, src/main/java/com/kyonggi/diet/review/favoriteReview/service/impl/FavoriteDietFoodReviewServiceImpl.java
좋아요 음식 리뷰 dto에 음식 리뷰 id값 추가
좋아요 음식 리뷰 dto에 음식 리뷰 id값 추가
=> refactor: fix favorite diet food review dto structure

src/main/java/com/kyonggi/diet/review/domain/DietFoodReview.java, src/main/java/com/kyonggi/diet/review/domain/RestaurantReview.java, src/main/java/com/kyonggi/diet/review/favoriteReview/domain/FavoriteDietFoodReview.java, src/main/java/com/kyonggi/diet/review/favoriteReview/domain/FavoriteRestaurantReview.java
좋아요 리뷰 id 생성 전략 변경
좋아요 리뷰 id 생성 전략 변경
=> refactor: fix strategy of favorite review id

Jenkinsfile, src/main/java/com/kyonggi/diet/auth/KakaoAuthController.java, src/main/java/com/kyonggi/diet/auth/KakaoAuthService.java
- 카카오 로그인 원인불명 에러 존재
- 젠킨스 구성요소 변경 필요
- 카카오 로그인을 위한 추가적인 에러 처리
- Jenkins를 새로운 aws 설정에 맞게 재구성
=> [FIX] 로그인 에러 처리 및 젠킨스 재구성

src/main/java/com/kyonggi/diet/review/controller/DietFoodReviewController.java
리뷰 조회 없을 시 빈 배열 반환으로 변경
리뷰 조회 없을 시 빈 배열 반환으로 변경
=> feat: fix Exception to null list

Jenkinsfile, src/main/resources/application.yml
#69 
미국지역 -> 한국지역 으로 이동
- 로그 레벨 변경
- Jenkins에 지정된 지역 변경
=> [CHORE] Migrate AWS Region

.idea/modules/diet.main.iml, src/main/java/com/kyonggi/diet/auth/config/WebSecurityConfig.java, src/main/resources/application.yml
Swagger URI가 노출되었음
- Spring security를 통해 swagger uri 차단
=> [FEAT] Deny swagger uri by spring-security
